# Generated by Django 5.2.6 on 2026-04-28 05:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0001_initial'),
        ('users', '0016_add_nutritionplan'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NutritionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_calories', models.FloatField()),
                ('protein_g', models.FloatField()),
                ('carbs_g', models.FloatField()),
                ('fat_g', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nutrition_plans', to='users.athleteprofile')),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_nutrition_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
