# Generated by Django 5.2.6 on 2026-04-28 05:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nutrition", "0002_add_nutritionplan"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="nutritionplan",
            name="athlete",
        ),
        migrations.AddField(
            model_name="nutritionplan",
            name="assigned_athletes",
            field=models.ManyToManyField(
                blank=True, related_name="nutrition_plans", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="nutritionplan",
            name="title",
            field=models.CharField(default="", max_length=255),
        ),
    ]
