version: "3.9"

services:
  db:
    image: postgres:17
    container_name: Athletica_db
    restart: always
    environment:
      POSTGRES_DB: users_db
      POSTGRES_USER: users_django
      POSTGRES_PASSWORD: password123
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: ./backend
    container_name: Athletica_web
    restart: always
    command: sh -c "python manage.py makemigrations users && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DJANGO_SETTINGS_MODULE: backend.settings
      DEBUG: "True"
      DB_NAME: users_db
      DB_USER: users_django
      DB_PASSWORD: password123
      DB_HOST: db
      DB_PORT: 5432

volumes:
  postgres_data: