# SonarQube / SonarCloud Project Configuration
sonar.projectKey=Athletica
sonar.organization=sahiansalome14
sonar.projectName=Athletica
sonar.projectVersion=1.0

# Path to source directories (comma-separated)
sonar.sources=backend,frontend/lib
# Path to test directories
sonar.tests=backend/tests,backend/nutrition/tests.py,backend/users/tests.py
# Inclusions for tests
sonar.test.inclusions=backend/**/tests.py,backend/**/tests/**

# Exclusions
sonar.exclusions=**/migrations/**, **/venv/**, **/.venv/**, **/build/**, **/.dart_tool/**, **/*.g.dart, **/*.freezed.dart, backend/manage.py, backend/backend/wsgi.py, backend/backend/asgi.py, backend/**/tests.py, backend/**/tests/**
sonar.coverage.exclusions=frontend/**

# --- Backend (Python) Configuration ---
sonar.python.version=3.12
# Relative path to coverage report
sonar.python.coverage.reportPaths=backend/coverage.xml

# --- Frontend (Dart/Flutter) Configuration ---
# Coverage ignored for frontend

# Encoding
sonar.sourceEncoding=UTF-8
