# Generated by Django 6.0.3 on 2026-03-20 03:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('routines', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='routine',
            name='assigned_athletes',
            field=models.ManyToManyField(blank=True, related_name='routines', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='routine',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_routines', to=settings.AUTH_USER_MODEL),
        ),
    ]
