# Generated by Django 6.0.3 on 2026-03-22 20:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routines', '0002_workoutsession_setlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='image_url',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='workoutsession',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
