# Generated by Django 6.0.3 on 2026-03-21 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routines', '0002_exercise_alter_routine_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='external_id',
            field=models.IntegerField(default=-1, unique=True),
        ),
    ]
