# Generated by Django 6.0.3 on 2026-03-22 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routines', '0003_exercise_external_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='routine',
            old_name='Difficulty',
            new_name='difficulty',
        ),
    ]
