# Generated by Django 6.0.3 on 2026-03-28 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routines', '0004_alter_exercise_image_url_alter_routine_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='muscle',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
