# Generated by Django 6.0.3 on 2026-03-28 17:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("routines", "0005_alter_exercise_description_alter_exercise_muscle"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exercise",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="exercise",
            name="image_url",
            field=models.TextField(blank=True, default="", null=True),
        ),
        migrations.AlterField(
            model_name="exercise",
            name="muscle",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
