# Generated by Django 6.0.3 on 2026-04-19 18:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("routines", "0007_alter_exercise_description_alter_exercise_image_url_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exercise",
            name="external_id",
            field=models.BigIntegerField(default=-1, unique=True),
        ),
        migrations.AlterField(
            model_name="exercise",
            name="muscle",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="exercise",
            name="name",
            field=models.CharField(max_length=255),
        ),
    ]
