# Generated by Django 6.0.3 on 2026-04-19 20:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_alter_goal_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="coachprofile",
            name="athletes",
            field=models.ManyToManyField(
                blank=True, related_name="managed_by_coaches", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
