# Generated by Django 6.0.3 on 2026-04-19 22:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0006_coachprofile_athletes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="goal",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
    ]
