# Generated by Django 6.0.4 on 2026-04-25 23:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0008_remove_coachprofile_business_address_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="coachprofile",
            old_name="experience",
            new_name="years_experience",
        ),
    ]
