# Generated by Django 6.0.3 on 2026-04-20 23:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0008_alter_goal_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="goal",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
    ]
