# Generated by Django 6.0.4 on 2026-04-28 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_merge_20260427_0304'),
        ('users', '0010_user_profile_settings_fields'),
    ]

    operations = [
    ]
