# Generated by Django 6.0.4 on 2026-05-16 20:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0017_alter_athleteprofile_id_alter_coachprofile_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="weightlog",
            name="date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
