# Generated by Django 6.0.2 on 2026-05-17 02:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0018_reminder"),
    ]

    operations = [
        migrations.AddField(
            model_name="reminder",
            name="recurrence",
            field=models.CharField(
                choices=[
                    ("none", "None"),
                    ("daily", "Daily"),
                    ("weekly", "Weekly"),
                    ("biweekly", "Biweekly"),
                    ("monthly", "Monthly"),
                ],
                default="none",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="reminder",
            name="timezone",
            field=models.CharField(
                default="UTC", help_text="IANA timezone for this reminder", max_length=50
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="timezone",
            field=models.CharField(
                default="UTC",
                help_text="IANA timezone (e.g., 'America/Bogota', 'America/New_York')",
                max_length=50,
            ),
        ),
    ]
