# Generated by Django 6.0.4 on 2026-05-17 00:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0019_follow"),
        ("users", "0019_reminder_recurrence_reminder_timezone_user_timezone"),
    ]

    operations = []
