# Generated by Django 6.0.2 on 2026-05-17 16:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0020_merge_20260517_0000"),
    ]

    operations = [
        migrations.CreateModel(
            name="Badge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "badge_type",
                    models.CharField(
                        choices=[
                            ("alimentacion", "Racha de Alimentación"),
                            ("ejercicio", "Racha de Ejercicio"),
                            ("completa", "Racha Completa"),
                            ("logros", "Contador de Logros"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "level",
                    models.IntegerField(help_text="Nivel/número de la insignia (1, 3, 7, etc.)"),
                ),
                (
                    "name",
                    models.CharField(help_text="Nombre descriptivo de la insignia", max_length=200),
                ),
                (
                    "description",
                    models.TextField(help_text="Descripción de cómo se obtiene esta insignia"),
                ),
                (
                    "svg_filename",
                    models.CharField(
                        help_text="Nombre del archivo SVG en backend/users/badges/svg/",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "unlock_condition",
                    models.TextField(
                        help_text="Descripción de la condición requerida para desbloquear"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Badges",
                "ordering": ["badge_type", "level"],
                "unique_together": {("badge_type", "level")},
            },
        ),
        migrations.CreateModel(
            name="UserBadge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("unlocked_at", models.DateTimeField(auto_now_add=True)),
                (
                    "badge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="unlocked_by",
                        to="users.badge",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="badges",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "User Badges",
                "ordering": ["-unlocked_at"],
                "unique_together": {("user", "badge")},
            },
        ),
    ]
